import { lazy } from 'react';
import type { UserRole } from '../types';

export type RouteFeatureFlag = 'pageVisibility';

export interface AppRoute {
    path: string;
    label: string;
    icon: string;
    section?: string;
    color?: string;
    showInSidebar?: boolean;
    showInBottomNav?: boolean;
    requiresAuth?: boolean;
    requiredRole?: UserRole | UserRole[];
    requiredPermission?: string;
    isDefaultHome?: boolean;
    featureFlag?: RouteFeatureFlag;
    component: React.LazyExoticComponent<React.ComponentType>;
}

const createLazyPage = (importer: () => Promise<{ default: React.ComponentType }>) => lazy(importer);

export const routesManifest: AppRoute[] = [
    {
        path: '/login',
        label: 'Login',
        icon: 'login',
        requiresAuth: false,
        component: createLazyPage(() => import('../pages/LoginPage')),
    },
    {
        path: '/dashboard',
        label: 'Dashboard',
        icon: 'dashboard',
        section: 'Principale',
        showInSidebar: true,
        showInBottomNav: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/DashboardPage')),
    },
    {
        path: '/notifications',
        label: 'Notifiche',
        icon: 'notifications',
        section: 'Principale',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/NotificationsPage')),
    },
    {
        path: '/staffing',
        label: 'Staffing',
        icon: 'calendar_month',
        section: 'Principale',
        showInSidebar: true,
        isDefaultHome: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/StaffingPage').then(module => ({ default: module.StaffingPage }))),
    },
    {
        path: '/workload',
        label: 'Carico Risorse',
        icon: 'groups',
        section: 'Principale',
        showInSidebar: true,
        showInBottomNav: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/WorkloadPage')),
    },
    {
        path: '/gantt',
        label: 'Gantt',
        icon: 'align_horizontal_left',
        section: 'Progetti',
        showInSidebar: true,
        showInBottomNav: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/GanttPage')),
    },
    {
        path: '/projects',
        label: 'Progetti',
        icon: 'folder',
        section: 'Progetti',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/ProjectsPage')),
    },
    {
        path: '/contracts',
        label: 'Contratti',
        icon: 'description',
        section: 'Progetti',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/ContractsPage').then(module => ({ default: module.ContractsPage }))),
    },
    {
        path: '/clients',
        label: 'Clienti',
        icon: 'domain',
        section: 'Progetti',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/ClientsPage')),
    },
    {
        path: '/forecasting',
        label: 'Forecasting',
        icon: 'trending_up',
        section: 'Progetti',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/ForecastingPage')),
    },
    {
        path: '/resources',
        label: 'Risorse',
        icon: 'person',
        section: 'Risorse',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/ResourcesPage')),
    },
    {
        path: '/skills',
        label: 'Competenze',
        icon: 'school',
        section: 'Risorse',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/SkillsPage')),
    },
    {
        path: '/certifications',
        label: 'Certificazioni',
        icon: 'verified',
        section: 'Risorse',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/CertificationsPage')),
    },
    {
        path: '/skill-analysis',
        label: 'Analisi Competenze',
        icon: 'insights',
        section: 'Risorse',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/SkillAnalysisPage')),
    },
    {
        path: '/roles',
        label: 'Ruoli',
        icon: 'badge',
        section: 'Risorse',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/RolesPage')),
    },
    {
        path: '/leaves',
        label: 'Assenze',
        icon: 'event_busy',
        section: 'Risorse',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/LeavePage')),
    },
    {
        path: '/resource-requests',
        label: 'Richieste Risorse',
        icon: 'assignment',
        section: 'Operatività',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/ResourceRequestPage').then(module => ({ default: module.ResourceRequestPage }))),
    },
    {
        path: '/interviews',
        label: 'Colloqui',
        icon: 'groups',
        section: 'Operatività',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/InterviewsPage')),
    },
    {
        path: '/skills-map',
        label: 'Mappa Competenze',
        icon: 'school',
        section: 'Operatività',
        showInSidebar: true,
        showInBottomNav: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/SkillsMapPage')),
    },
    {
        path: '/staffing-visualization',
        label: 'Visualizzazione Staffing',
        icon: 'hub',
        section: 'Operatività',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/StaffingVisualizationPage')),
    },
    {
        path: '/manuale-utente',
        label: 'Manuale Utente',
        icon: 'menu_book',
        section: 'Supporto',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/UserManualPage')),
    },
    {
        path: '/simple-user-manual',
        label: 'Guida Assenze',
        icon: 'help_center',
        section: 'Supporto',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/SimpleUserManualPage')),
    },
    {
        path: '/reports',
        label: 'Report',
        icon: 'bar_chart',
        section: 'Supporto',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/ReportsPage')),
    },
    {
        path: '/calendar',
        label: 'Calendario Aziendale',
        icon: 'event',
        section: 'Configurazione',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/CalendarPage')),
    },
    {
        path: '/config',
        label: 'Opzioni',
        icon: 'settings',
        section: 'Configurazione',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/ConfigPage')),
    },
    {
        path: '/test-staffing',
        label: 'Test Staffing',
        icon: 'science',
        section: 'Configurazione',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/TestStaffingPage')),
    },
    {
        path: '/import',
        label: 'Importa Dati',
        icon: 'upload',
        section: 'Dati',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/ImportPage')),
    },
    {
        path: '/export',
        label: 'Esporta Dati',
        icon: 'download',
        section: 'Dati',
        showInSidebar: true,
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/ExportPage')),
    },
    {
        path: '/admin-settings',
        label: 'Impostazioni Admin',
        icon: 'admin_panel_settings',
        section: 'Amministrazione',
        showInSidebar: true,
        requiredRole: 'ADMIN',
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/AdminSettingsPage')),
    },
    {
        path: '/db-inspector',
        label: 'Database Inspector',
        icon: 'database',
        section: 'Amministrazione',
        showInSidebar: true,
        requiredRole: 'ADMIN',
        featureFlag: 'pageVisibility',
        component: createLazyPage(() => import('../pages/DbInspectorPage')),
    },
];